A20.1: NFnCall parse check
prasannameta/PSI pull request #2
Opened 2023-04-30 04:56 UTC by prasannameta

Arvind,

Checked Function call parsing.
Working on Const declarations and commit in the same branch with A20.2 commit.

Thanks,

2023-04-30 11:06 UTC, tarydon requested changes

2023-04-30 11:06 UTC, tarydon commented on Parser/Lexer/Tokenizer.cs
> +         return (new[] { '.', 'e', 'E' }.Any (text.Contains)) ?
Even simpler:
`".eE".Any (text.Contains)`

2023-04-30 11:06 UTC, tarydon commented on Parser/Lexer/Tokenizer.cs
> +      while (mN < mText.Length && mText[mN++] != '"') ;
This is not good style. It will be confusing since it looks like you added a ; by mistake. The { } style is preferred.

2023-04-30 11:06 UTC, tarydon commented on Parser/Types/TypeAnalyze.cs
> +      return Void;
What about checking the types and numbers of parameters?

2023-04-30 11:06 UTC, tarydon commented on Parser/Types/TypeAnalyze.cs
> +      if (f.Params.Length != fnDecl.Params.Length) throw new ParseException (f.Name, "Function parameters do not match equal");
Confusing error message - reword.

2023-05-01 14:18 UTC, prasannameta commented
Arvind,

Added Const declarations for review.
Working on review changes and fixes, will push review fixes in the next commit.

Thanks,

2023-07-21 12:36 UTC, closed without merging